{
  "formatVersion": "1.1",
  "component": {
    "group": "gov.noaa.gsd.fiqas",
    "module": "verification",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6",
      "buildId": "fghbpmfa4rf33pzzdpkwxbgusy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "gov.noaa.gsd.fiqas",
          "module": "util",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "gov.noaa.gsd.fiqas",
          "module": "math",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "gov.noaa.gsd.fiqas",
          "module": "cartography",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "verification-1.1.jar",
          "url": "verification-1.1.jar",
          "size": 369692,
          "sha512": "31263734f9b421c8dbb7353b663ca4389d47f6b9e39879a6732cec8b9f5ff074a17edb321689f2f0e952c96a203265be20a7840278c2a10167060cb58a40afad",
          "sha256": "549b288601d62e4fe3d8ba4b54fca8a0bfea43b98bd651ffc09b97464ab5c3fc",
          "sha1": "be9d17bea6e31fda497dd663cd617d085270dd72",
          "md5": "36490a40a42cad40bf7f34da3b3fa58b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "gov.noaa.gsd.fiqas",
          "module": "util",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "gov.noaa.gsd.fiqas",
          "module": "math",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "gov.noaa.gsd.fiqas",
          "module": "cartography",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "verification-1.1.jar",
          "url": "verification-1.1.jar",
          "size": 369692,
          "sha512": "31263734f9b421c8dbb7353b663ca4389d47f6b9e39879a6732cec8b9f5ff074a17edb321689f2f0e952c96a203265be20a7840278c2a10167060cb58a40afad",
          "sha256": "549b288601d62e4fe3d8ba4b54fca8a0bfea43b98bd651ffc09b97464ab5c3fc",
          "sha1": "be9d17bea6e31fda497dd663cd617d085270dd72",
          "md5": "36490a40a42cad40bf7f34da3b3fa58b"
        }
      ]
    }
  ]
}
