{
  "formatVersion": "1.1",
  "component": {
    "group": "gov.noaa.gsd.fiqas",
    "module": "util",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "util-1.1.jar",
          "url": "util-1.1.jar",
          "size": 742015,
          "sha512": "88664e3c31fba6c52adcc18eb9d5a105f572a1ad16231b96229a35b4c52f9ccf16d6c39382422d27203379d2ea9d2725f757e3394e907ee87c6ccd5725f19b06",
          "sha256": "bd6c817ec8c1cd2bd4b0dd1677bf868f83d56359841b7af6b1da8490657f29d1",
          "sha1": "8dfa34d4b189083dfd0dd11aff2553bdee342caf",
          "md5": "78ce9499b72fb2a693ea079b4263f15c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "gov.noaa.gsd.fiqas",
          "module": "math",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "jfree",
          "module": "jfreechart",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "ucar",
          "module": "netcdfAll",
          "version": {
            "requires": "4.6"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "9.3-1104-jdbc41"
          }
        },
        {
          "group": "mysql",
          "module": "mysql-connector-java",
          "version": {
            "requires": "5.1.39"
          }
        }
      ],
      "files": [
        {
          "name": "util-1.1.jar",
          "url": "util-1.1.jar",
          "size": 742015,
          "sha512": "88664e3c31fba6c52adcc18eb9d5a105f572a1ad16231b96229a35b4c52f9ccf16d6c39382422d27203379d2ea9d2725f757e3394e907ee87c6ccd5725f19b06",
          "sha256": "bd6c817ec8c1cd2bd4b0dd1677bf868f83d56359841b7af6b1da8490657f29d1",
          "sha1": "8dfa34d4b189083dfd0dd11aff2553bdee342caf",
          "md5": "78ce9499b72fb2a693ea079b4263f15c"
        }
      ]
    }
  ]
}
