{
  "formatVersion": "1.1",
  "component": {
    "group": "gov.noaa.gsd.fiqas",
    "module": "cartography",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cartography-1.1.jar",
          "url": "cartography-1.1.jar",
          "size": 73166,
          "sha512": "ab112729ea5d7bd663783f3cb16d997068fba916c6279ed109d928223e9bdc84f36180cb945b9ded4045f894f0135830310ff553ac16f208ee594b1f125ca996",
          "sha256": "d1363670127f3be0ce9a34e1e48adef4679e23d5ecf3daf11a25fa17fc960982",
          "sha1": "6b8abda30aea8129fb2974bb79039683c7d56847",
          "md5": "bfb762d207f85764e1f0145320761db9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "16+"
          }
        },
        {
          "group": "ucar",
          "module": "netcdfAll",
          "version": {
            "requires": "4.6"
          }
        },
        {
          "group": "gov.noaa.gsd.fiqas",
          "module": "math",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "gov.noaa.gsd.fiqas",
          "module": "util",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "cartography-1.1.jar",
          "url": "cartography-1.1.jar",
          "size": 73166,
          "sha512": "ab112729ea5d7bd663783f3cb16d997068fba916c6279ed109d928223e9bdc84f36180cb945b9ded4045f894f0135830310ff553ac16f208ee594b1f125ca996",
          "sha256": "d1363670127f3be0ce9a34e1e48adef4679e23d5ecf3daf11a25fa17fc960982",
          "sha1": "6b8abda30aea8129fb2974bb79039683c7d56847",
          "md5": "bfb762d207f85764e1f0145320761db9"
        }
      ]
    }
  ]
}
