{
  "formatVersion": "1.1",
  "component": {
    "group": "gov.noaa.gsd.fiqas",
    "module": "cartography",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6",
      "buildId": "fghbpmfa4rf33pzzdpkwxbgusy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "gov.noaa.gsd.fiqas",
          "module": "math",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "gov.noaa.gsd.fiqas",
          "module": "util",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "cartography-1.1.jar",
          "url": "cartography-1.1.jar",
          "size": 67751,
          "sha512": "fc1446dda28d84b59d542bbfdb0a2c64d5762bc9a1c863855fdaea350efa579ba503fd8fcc6acb0a5b7665d57e824d4684948ff21a805f9f1c62e0b07a5dcdf1",
          "sha256": "a75ed9f690af961101a3385c172dec3472db85f0f808ddf1567067166a0e769a",
          "sha1": "2ac604e23954c808c3dc453edd75a6923e37ce5a",
          "md5": "80a190a9efbaedbfb4c735a2c83926d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "gov.noaa.gsd.fiqas",
          "module": "math",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "gov.noaa.gsd.fiqas",
          "module": "util",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "cartography-1.1.jar",
          "url": "cartography-1.1.jar",
          "size": 67751,
          "sha512": "fc1446dda28d84b59d542bbfdb0a2c64d5762bc9a1c863855fdaea350efa579ba503fd8fcc6acb0a5b7665d57e824d4684948ff21a805f9f1c62e0b07a5dcdf1",
          "sha256": "a75ed9f690af961101a3385c172dec3472db85f0f808ddf1567067166a0e769a",
          "sha1": "2ac604e23954c808c3dc453edd75a6923e37ce5a",
          "md5": "80a190a9efbaedbfb4c735a2c83926d1"
        }
      ]
    }
  ]
}
