{
  "formatVersion": "1.1",
  "component": {
    "group": "gov.noaa.gsd.fiqas",
    "module": "math",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6",
      "buildId": "fghbpmfa4rf33pzzdpkwxbgusy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "math-1.1.jar",
          "url": "math-1.1.jar",
          "size": 162822,
          "sha512": "50104b09840a389f2cc062ad6fac4152f33585adaccd56f3933203125a2b80147b1a423108adfb9e6b381d8f240ba29964087fee977008af23a87f4b3289ceb1",
          "sha256": "a476a5c28c4c5bfffcfc5e05a16c7bd1af0f194173ff53004496b9c72e25c441",
          "sha1": "615999193151713b55327179fc502e6e58cf2b8b",
          "md5": "07b52564f81b76a7815c673c25d45b6a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "math-1.1.jar",
          "url": "math-1.1.jar",
          "size": 162822,
          "sha512": "50104b09840a389f2cc062ad6fac4152f33585adaccd56f3933203125a2b80147b1a423108adfb9e6b381d8f240ba29964087fee977008af23a87f4b3289ceb1",
          "sha256": "a476a5c28c4c5bfffcfc5e05a16c7bd1af0f194173ff53004496b9c72e25c441",
          "sha1": "615999193151713b55327179fc502e6e58cf2b8b",
          "md5": "07b52564f81b76a7815c673c25d45b6a"
        }
      ]
    }
  ]
}
