name: Run Pytest
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        python-version: [ "3.11" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov python-dateutil==2.8.2 pint==0.21 importlib-metadata==6.7.0
      #- name: Install conda env
      #  uses: conda-incubator/setup-miniconda@v2
      #  with:
      #    auto-update-conda: true
      #    python-version: ${{ matrix.python-version }}
      #    channels: conda-forge
      #- name: Install dependencies with conda
      #  run: |
      #    conda install pytest python-dateutil==2.8.2 pint==0.21
      - name: Test with pytest
        working-directory: python/idsse_common/test
        run: |
          pytest --cov=../idsse/common --cov-report=term